sonar.projectKey=sports-center-management-system-uat-be
sonar.projectName=Sports Center Management System UAT BE
sonar.sources=src,prisma
sonar.tests=tests
sonar.test.inclusions=tests/**/*.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/prisma/data/**
sonar.coverage.exclusions=**/*.spec.ts,**/*.test.ts,tests/**,prisma/seed.ts
sonar.sourceEncoding=UTF-8